apiVersion: v1
kind: PersistentVolume
metadata:
 name: postgres-data-pv-2
 labels:
   type: local
spec:
 storageClassName: manual
 capacity:
   storage: 100Mi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: "/home/postgresdata"
   type: Directory
