apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "todo.fullname" . }}-todo
  name: todo-proxy
  labels:
    todo-app-service: todo-proxy
spec:
  type: LoadBalancer
  selector:
    todo-app-pod: todo-proxy
  ports:
  - name: "http"
    port: {{ .Values.services.todoProxy.port}}
    targetPort: 80

